spring.application.name=flowforge
server.port=8080
spring.jackson.serialization.write-dates-as-timestamps=false
flowforge.temporal.target=${TEMPORAL_ADDRESS:127.0.0.1:7233}
flowforge.temporal.namespace=${TEMPORAL_NAMESPACE:default}
flowforge.temporal.task-queue=${TEMPORAL_TASK_QUEUE:flowforge}
flowforge.workflow-directory=${FLOWFORGE_WORKFLOW_DIRECTORY:workflows}
